CREATE SCHEMA IF NOT EXISTS people_schema;

CREATE TABLE IF NOT EXISTS people_schema.person
(
    id BIGINT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL
)